name: DKAROCKS
favicon: null
layout_spectrum: 0.49639
typography_spectrum: 0.3024709385354072
title: "Detroit Kickball Association. Kickin' Balls and takin' names since 2008!"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ce0000'
    - '#000000'
    - '#e88a8b'
    - '#3b3b3b'
  brandStrength: 0.8125
  lightness: 0
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
